# Generated by Django 5.0.6 on 2024-12-08 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discount_price_product_discounted_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Wedding'), ('ML', 'Reception'), ('LS', 'Birthday'), ('MS', 'Jamai Bou'), ('PN', 'Office Ferwell'), ('GH', 'Office Party'), ('CZ', 'Ghorar Gari'), ('IC', 'All Events Pakage')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('category', models.CharField(choices=[('CR', 'Wedding'), ('ML', 'Reception'), ('LS', 'Birthday'), ('MS', 'Jamai Bou'), ('PN', 'Office Ferwell'), ('GH', 'Office Party'), ('CZ', 'Ghorar Gari'), ('IC', 'All Events Pakage')], max_length=2)),
                ('Product_image', models.ImageField(upload_to='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
